name: Run Scraper - Update data # 워크플로우 이름 지정

on:
  schedule:
    - cron:  '* * * * *' # 주기적으로 실행하기 위한 스케줄링 - cron 설정

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Scraper with python
      run: |
        python "scrap.py"
    - name: Commits
      run: |
        git config --local user.email mskjh6@naver.com
        git config --local user.name kimjanghyun1010 # 커밋에 포함될 이름
        git add scrap.json
        git commit -m "Auto - Update data with Scraping" # 커밋 메세지
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
